import type { Metadata } from 'next';
import { Red_Hat_Mono } from 'next/font/google';
import './globals.css';


const inter = Red_Hat_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="aqua">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
